/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterAdminRouteImport } from './routes/water-admin'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaterAdminStockRouteImport } from './routes/water-admin.stock'
import { Route as WaterAdminSalesRouteImport } from './routes/water-admin.sales'
import { Route as WaterAdminRequestsRouteImport } from './routes/water-admin.requests'
import { Route as WaterAdminReportsRouteImport } from './routes/water-admin.reports'
import { Route as WaterAdminExpensesRouteImport } from './routes/water-admin.expenses'
import { Route as WaterAdminDashboardRouteImport } from './routes/water-admin.dashboard'
import { Route as WaterAdminCashiersRouteImport } from './routes/water-admin.cashiers'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminShopsRouteImport } from './routes/super-admin.shops'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminExpensesRouteImport } from './routes/super-admin.expenses'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as SuperAdminAssetsRouteImport } from './routes/super-admin.assets'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as RbAdminDashboardRouteImport } from './routes/rb-admin.dashboard'
import { Route as DeliveryAdminDashboardRouteImport } from './routes/delivery-admin.dashboard'

const WaterAdminRoute = WaterAdminRouteImport.update({
  id: '/water-admin',
  path: '/water-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterAdminStockRoute = WaterAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminSalesRoute = WaterAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminRequestsRoute = WaterAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminReportsRoute = WaterAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminExpensesRoute = WaterAdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminDashboardRoute = WaterAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminCashiersRoute = WaterAdminCashiersRouteImport.update({
  id: '/cashiers',
  path: '/cashiers',
  getParentRoute: () => WaterAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminShopsRoute = SuperAdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminExpensesRoute = SuperAdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAssetsRoute = SuperAdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperAdminRoute,
} as any)
const RbAdminDashboardRoute = RbAdminDashboardRouteImport.update({
  id: '/rb-admin/dashboard',
  path: '/rb-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryAdminDashboardRoute = DeliveryAdminDashboardRouteImport.update({
  id: '/delivery-admin/dashboard',
  path: '/delivery-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/water-admin': typeof WaterAdminRouteWithChildren
  '/delivery-admin/dashboard': typeof DeliveryAdminDashboardRoute
  '/rb-admin/dashboard': typeof RbAdminDashboardRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/assets': typeof SuperAdminAssetsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/expenses': typeof SuperAdminExpensesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/shops': typeof SuperAdminShopsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/water-admin/cashiers': typeof WaterAdminCashiersRoute
  '/water-admin/dashboard': typeof WaterAdminDashboardRoute
  '/water-admin/expenses': typeof WaterAdminExpensesRoute
  '/water-admin/reports': typeof WaterAdminReportsRoute
  '/water-admin/requests': typeof WaterAdminRequestsRoute
  '/water-admin/sales': typeof WaterAdminSalesRoute
  '/water-admin/stock': typeof WaterAdminStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/water-admin': typeof WaterAdminRouteWithChildren
  '/delivery-admin/dashboard': typeof DeliveryAdminDashboardRoute
  '/rb-admin/dashboard': typeof RbAdminDashboardRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/assets': typeof SuperAdminAssetsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/expenses': typeof SuperAdminExpensesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/shops': typeof SuperAdminShopsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/water-admin/cashiers': typeof WaterAdminCashiersRoute
  '/water-admin/dashboard': typeof WaterAdminDashboardRoute
  '/water-admin/expenses': typeof WaterAdminExpensesRoute
  '/water-admin/reports': typeof WaterAdminReportsRoute
  '/water-admin/requests': typeof WaterAdminRequestsRoute
  '/water-admin/sales': typeof WaterAdminSalesRoute
  '/water-admin/stock': typeof WaterAdminStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/water-admin': typeof WaterAdminRouteWithChildren
  '/delivery-admin/dashboard': typeof DeliveryAdminDashboardRoute
  '/rb-admin/dashboard': typeof RbAdminDashboardRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/assets': typeof SuperAdminAssetsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/expenses': typeof SuperAdminExpensesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/shops': typeof SuperAdminShopsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/water-admin/cashiers': typeof WaterAdminCashiersRoute
  '/water-admin/dashboard': typeof WaterAdminDashboardRoute
  '/water-admin/expenses': typeof WaterAdminExpensesRoute
  '/water-admin/reports': typeof WaterAdminReportsRoute
  '/water-admin/requests': typeof WaterAdminRequestsRoute
  '/water-admin/sales': typeof WaterAdminSalesRoute
  '/water-admin/stock': typeof WaterAdminStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/super-admin'
    | '/water-admin'
    | '/delivery-admin/dashboard'
    | '/rb-admin/dashboard'
    | '/super-admin/analytics'
    | '/super-admin/assets'
    | '/super-admin/dashboard'
    | '/super-admin/expenses'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/shops'
    | '/super-admin/users'
    | '/water-admin/cashiers'
    | '/water-admin/dashboard'
    | '/water-admin/expenses'
    | '/water-admin/reports'
    | '/water-admin/requests'
    | '/water-admin/sales'
    | '/water-admin/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/super-admin'
    | '/water-admin'
    | '/delivery-admin/dashboard'
    | '/rb-admin/dashboard'
    | '/super-admin/analytics'
    | '/super-admin/assets'
    | '/super-admin/dashboard'
    | '/super-admin/expenses'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/shops'
    | '/super-admin/users'
    | '/water-admin/cashiers'
    | '/water-admin/dashboard'
    | '/water-admin/expenses'
    | '/water-admin/reports'
    | '/water-admin/requests'
    | '/water-admin/sales'
    | '/water-admin/stock'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/super-admin'
    | '/water-admin'
    | '/delivery-admin/dashboard'
    | '/rb-admin/dashboard'
    | '/super-admin/analytics'
    | '/super-admin/assets'
    | '/super-admin/dashboard'
    | '/super-admin/expenses'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/shops'
    | '/super-admin/users'
    | '/water-admin/cashiers'
    | '/water-admin/dashboard'
    | '/water-admin/expenses'
    | '/water-admin/reports'
    | '/water-admin/requests'
    | '/water-admin/sales'
    | '/water-admin/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  WaterAdminRoute: typeof WaterAdminRouteWithChildren
  DeliveryAdminDashboardRoute: typeof DeliveryAdminDashboardRoute
  RbAdminDashboardRoute: typeof RbAdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-admin': {
      id: '/water-admin'
      path: '/water-admin'
      fullPath: '/water-admin'
      preLoaderRoute: typeof WaterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-admin/stock': {
      id: '/water-admin/stock'
      path: '/stock'
      fullPath: '/water-admin/stock'
      preLoaderRoute: typeof WaterAdminStockRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/sales': {
      id: '/water-admin/sales'
      path: '/sales'
      fullPath: '/water-admin/sales'
      preLoaderRoute: typeof WaterAdminSalesRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/requests': {
      id: '/water-admin/requests'
      path: '/requests'
      fullPath: '/water-admin/requests'
      preLoaderRoute: typeof WaterAdminRequestsRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/reports': {
      id: '/water-admin/reports'
      path: '/reports'
      fullPath: '/water-admin/reports'
      preLoaderRoute: typeof WaterAdminReportsRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/expenses': {
      id: '/water-admin/expenses'
      path: '/expenses'
      fullPath: '/water-admin/expenses'
      preLoaderRoute: typeof WaterAdminExpensesRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/dashboard': {
      id: '/water-admin/dashboard'
      path: '/dashboard'
      fullPath: '/water-admin/dashboard'
      preLoaderRoute: typeof WaterAdminDashboardRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/cashiers': {
      id: '/water-admin/cashiers'
      path: '/cashiers'
      fullPath: '/water-admin/cashiers'
      preLoaderRoute: typeof WaterAdminCashiersRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/shops': {
      id: '/super-admin/shops'
      path: '/shops'
      fullPath: '/super-admin/shops'
      preLoaderRoute: typeof SuperAdminShopsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/expenses': {
      id: '/super-admin/expenses'
      path: '/expenses'
      fullPath: '/super-admin/expenses'
      preLoaderRoute: typeof SuperAdminExpensesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/assets': {
      id: '/super-admin/assets'
      path: '/assets'
      fullPath: '/super-admin/assets'
      preLoaderRoute: typeof SuperAdminAssetsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/rb-admin/dashboard': {
      id: '/rb-admin/dashboard'
      path: '/rb-admin/dashboard'
      fullPath: '/rb-admin/dashboard'
      preLoaderRoute: typeof RbAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-admin/dashboard': {
      id: '/delivery-admin/dashboard'
      path: '/delivery-admin/dashboard'
      fullPath: '/delivery-admin/dashboard'
      preLoaderRoute: typeof DeliveryAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminAssetsRoute: typeof SuperAdminAssetsRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminExpensesRoute: typeof SuperAdminExpensesRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminShopsRoute: typeof SuperAdminShopsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminAssetsRoute: SuperAdminAssetsRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminExpensesRoute: SuperAdminExpensesRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminShopsRoute: SuperAdminShopsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface WaterAdminRouteChildren {
  WaterAdminCashiersRoute: typeof WaterAdminCashiersRoute
  WaterAdminDashboardRoute: typeof WaterAdminDashboardRoute
  WaterAdminExpensesRoute: typeof WaterAdminExpensesRoute
  WaterAdminReportsRoute: typeof WaterAdminReportsRoute
  WaterAdminRequestsRoute: typeof WaterAdminRequestsRoute
  WaterAdminSalesRoute: typeof WaterAdminSalesRoute
  WaterAdminStockRoute: typeof WaterAdminStockRoute
}

const WaterAdminRouteChildren: WaterAdminRouteChildren = {
  WaterAdminCashiersRoute: WaterAdminCashiersRoute,
  WaterAdminDashboardRoute: WaterAdminDashboardRoute,
  WaterAdminExpensesRoute: WaterAdminExpensesRoute,
  WaterAdminReportsRoute: WaterAdminReportsRoute,
  WaterAdminRequestsRoute: WaterAdminRequestsRoute,
  WaterAdminSalesRoute: WaterAdminSalesRoute,
  WaterAdminStockRoute: WaterAdminStockRoute,
}

const WaterAdminRouteWithChildren = WaterAdminRoute._addFileChildren(
  WaterAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  WaterAdminRoute: WaterAdminRouteWithChildren,
  DeliveryAdminDashboardRoute: DeliveryAdminDashboardRoute,
  RbAdminDashboardRoute: RbAdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
