/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterAdminRouteImport } from './routes/water-admin'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as RbAdminRouteImport } from './routes/rb-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryAdminRouteImport } from './routes/delivery-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaterAdminStockRouteImport } from './routes/water-admin.stock'
import { Route as WaterAdminRequestsRouteImport } from './routes/water-admin.requests'
import { Route as WaterAdminReportsRouteImport } from './routes/water-admin.reports'
import { Route as WaterAdminRefundsRouteImport } from './routes/water-admin.refunds'
import { Route as WaterAdminExpensesRouteImport } from './routes/water-admin.expenses'
import { Route as WaterAdminDashboardRouteImport } from './routes/water-admin.dashboard'
import { Route as WaterAdminCustomersRouteImport } from './routes/water-admin.customers'
import { Route as WaterAdminCashiersRouteImport } from './routes/water-admin.cashiers'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminShopsRouteImport } from './routes/super-admin.shops'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminExpensesRouteImport } from './routes/super-admin.expenses'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as SuperAdminAssetsRouteImport } from './routes/super-admin.assets'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as RbAdminReportsRouteImport } from './routes/rb-admin.reports'
import { Route as RbAdminDashboardRouteImport } from './routes/rb-admin.dashboard'
import { Route as DeliveryAdminReportsRouteImport } from './routes/delivery-admin.reports'
import { Route as DeliveryAdminFuelRouteImport } from './routes/delivery-admin.fuel'
import { Route as DeliveryAdminDriversRouteImport } from './routes/delivery-admin.drivers'
import { Route as DeliveryAdminDashboardRouteImport } from './routes/delivery-admin.dashboard'

const WaterAdminRoute = WaterAdminRouteImport.update({
  id: '/water-admin',
  path: '/water-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RbAdminRoute = RbAdminRouteImport.update({
  id: '/rb-admin',
  path: '/rb-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryAdminRoute = DeliveryAdminRouteImport.update({
  id: '/delivery-admin',
  path: '/delivery-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterAdminStockRoute = WaterAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminRequestsRoute = WaterAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminReportsRoute = WaterAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminRefundsRoute = WaterAdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminExpensesRoute = WaterAdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminDashboardRoute = WaterAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminCustomersRoute = WaterAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => WaterAdminRoute,
} as any)
const WaterAdminCashiersRoute = WaterAdminCashiersRouteImport.update({
  id: '/cashiers',
  path: '/cashiers',
  getParentRoute: () => WaterAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminShopsRoute = SuperAdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminExpensesRoute = SuperAdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAssetsRoute = SuperAdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperAdminRoute,
} as any)
const RbAdminReportsRoute = RbAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => RbAdminRoute,
} as any)
const RbAdminDashboardRoute = RbAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RbAdminRoute,
} as any)
const DeliveryAdminReportsRoute = DeliveryAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DeliveryAdminRoute,
} as any)
const DeliveryAdminFuelRoute = DeliveryAdminFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => DeliveryAdminRoute,
} as any)
const DeliveryAdminDriversRoute = DeliveryAdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => DeliveryAdminRoute,
} as any)
const DeliveryAdminDashboardRoute = DeliveryAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DeliveryAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delivery-admin': typeof DeliveryAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/rb-admin': typeof RbAdminRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/water-admin': typeof WaterAdminRouteWithChildren
  '/delivery-admin/dashboard': typeof DeliveryAdminDashboardRoute
  '/delivery-admin/drivers': typeof DeliveryAdminDriversRoute
  '/delivery-admin/fuel': typeof DeliveryAdminFuelRoute
  '/delivery-admin/reports': typeof DeliveryAdminReportsRoute
  '/rb-admin/dashboard': typeof RbAdminDashboardRoute
  '/rb-admin/reports': typeof RbAdminReportsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/assets': typeof SuperAdminAssetsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/expenses': typeof SuperAdminExpensesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/shops': typeof SuperAdminShopsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/water-admin/cashiers': typeof WaterAdminCashiersRoute
  '/water-admin/customers': typeof WaterAdminCustomersRoute
  '/water-admin/dashboard': typeof WaterAdminDashboardRoute
  '/water-admin/expenses': typeof WaterAdminExpensesRoute
  '/water-admin/refunds': typeof WaterAdminRefundsRoute
  '/water-admin/reports': typeof WaterAdminReportsRoute
  '/water-admin/requests': typeof WaterAdminRequestsRoute
  '/water-admin/stock': typeof WaterAdminStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delivery-admin': typeof DeliveryAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/rb-admin': typeof RbAdminRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/water-admin': typeof WaterAdminRouteWithChildren
  '/delivery-admin/dashboard': typeof DeliveryAdminDashboardRoute
  '/delivery-admin/drivers': typeof DeliveryAdminDriversRoute
  '/delivery-admin/fuel': typeof DeliveryAdminFuelRoute
  '/delivery-admin/reports': typeof DeliveryAdminReportsRoute
  '/rb-admin/dashboard': typeof RbAdminDashboardRoute
  '/rb-admin/reports': typeof RbAdminReportsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/assets': typeof SuperAdminAssetsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/expenses': typeof SuperAdminExpensesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/shops': typeof SuperAdminShopsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/water-admin/cashiers': typeof WaterAdminCashiersRoute
  '/water-admin/customers': typeof WaterAdminCustomersRoute
  '/water-admin/dashboard': typeof WaterAdminDashboardRoute
  '/water-admin/expenses': typeof WaterAdminExpensesRoute
  '/water-admin/refunds': typeof WaterAdminRefundsRoute
  '/water-admin/reports': typeof WaterAdminReportsRoute
  '/water-admin/requests': typeof WaterAdminRequestsRoute
  '/water-admin/stock': typeof WaterAdminStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delivery-admin': typeof DeliveryAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/rb-admin': typeof RbAdminRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/water-admin': typeof WaterAdminRouteWithChildren
  '/delivery-admin/dashboard': typeof DeliveryAdminDashboardRoute
  '/delivery-admin/drivers': typeof DeliveryAdminDriversRoute
  '/delivery-admin/fuel': typeof DeliveryAdminFuelRoute
  '/delivery-admin/reports': typeof DeliveryAdminReportsRoute
  '/rb-admin/dashboard': typeof RbAdminDashboardRoute
  '/rb-admin/reports': typeof RbAdminReportsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/assets': typeof SuperAdminAssetsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/expenses': typeof SuperAdminExpensesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/shops': typeof SuperAdminShopsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/water-admin/cashiers': typeof WaterAdminCashiersRoute
  '/water-admin/customers': typeof WaterAdminCustomersRoute
  '/water-admin/dashboard': typeof WaterAdminDashboardRoute
  '/water-admin/expenses': typeof WaterAdminExpensesRoute
  '/water-admin/refunds': typeof WaterAdminRefundsRoute
  '/water-admin/reports': typeof WaterAdminReportsRoute
  '/water-admin/requests': typeof WaterAdminRequestsRoute
  '/water-admin/stock': typeof WaterAdminStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delivery-admin'
    | '/login'
    | '/rb-admin'
    | '/super-admin'
    | '/water-admin'
    | '/delivery-admin/dashboard'
    | '/delivery-admin/drivers'
    | '/delivery-admin/fuel'
    | '/delivery-admin/reports'
    | '/rb-admin/dashboard'
    | '/rb-admin/reports'
    | '/super-admin/analytics'
    | '/super-admin/assets'
    | '/super-admin/dashboard'
    | '/super-admin/expenses'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/shops'
    | '/super-admin/users'
    | '/water-admin/cashiers'
    | '/water-admin/customers'
    | '/water-admin/dashboard'
    | '/water-admin/expenses'
    | '/water-admin/refunds'
    | '/water-admin/reports'
    | '/water-admin/requests'
    | '/water-admin/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delivery-admin'
    | '/login'
    | '/rb-admin'
    | '/super-admin'
    | '/water-admin'
    | '/delivery-admin/dashboard'
    | '/delivery-admin/drivers'
    | '/delivery-admin/fuel'
    | '/delivery-admin/reports'
    | '/rb-admin/dashboard'
    | '/rb-admin/reports'
    | '/super-admin/analytics'
    | '/super-admin/assets'
    | '/super-admin/dashboard'
    | '/super-admin/expenses'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/shops'
    | '/super-admin/users'
    | '/water-admin/cashiers'
    | '/water-admin/customers'
    | '/water-admin/dashboard'
    | '/water-admin/expenses'
    | '/water-admin/refunds'
    | '/water-admin/reports'
    | '/water-admin/requests'
    | '/water-admin/stock'
  id:
    | '__root__'
    | '/'
    | '/delivery-admin'
    | '/login'
    | '/rb-admin'
    | '/super-admin'
    | '/water-admin'
    | '/delivery-admin/dashboard'
    | '/delivery-admin/drivers'
    | '/delivery-admin/fuel'
    | '/delivery-admin/reports'
    | '/rb-admin/dashboard'
    | '/rb-admin/reports'
    | '/super-admin/analytics'
    | '/super-admin/assets'
    | '/super-admin/dashboard'
    | '/super-admin/expenses'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/shops'
    | '/super-admin/users'
    | '/water-admin/cashiers'
    | '/water-admin/customers'
    | '/water-admin/dashboard'
    | '/water-admin/expenses'
    | '/water-admin/refunds'
    | '/water-admin/reports'
    | '/water-admin/requests'
    | '/water-admin/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveryAdminRoute: typeof DeliveryAdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RbAdminRoute: typeof RbAdminRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  WaterAdminRoute: typeof WaterAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-admin': {
      id: '/water-admin'
      path: '/water-admin'
      fullPath: '/water-admin'
      preLoaderRoute: typeof WaterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rb-admin': {
      id: '/rb-admin'
      path: '/rb-admin'
      fullPath: '/rb-admin'
      preLoaderRoute: typeof RbAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-admin': {
      id: '/delivery-admin'
      path: '/delivery-admin'
      fullPath: '/delivery-admin'
      preLoaderRoute: typeof DeliveryAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-admin/stock': {
      id: '/water-admin/stock'
      path: '/stock'
      fullPath: '/water-admin/stock'
      preLoaderRoute: typeof WaterAdminStockRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/requests': {
      id: '/water-admin/requests'
      path: '/requests'
      fullPath: '/water-admin/requests'
      preLoaderRoute: typeof WaterAdminRequestsRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/reports': {
      id: '/water-admin/reports'
      path: '/reports'
      fullPath: '/water-admin/reports'
      preLoaderRoute: typeof WaterAdminReportsRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/refunds': {
      id: '/water-admin/refunds'
      path: '/refunds'
      fullPath: '/water-admin/refunds'
      preLoaderRoute: typeof WaterAdminRefundsRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/expenses': {
      id: '/water-admin/expenses'
      path: '/expenses'
      fullPath: '/water-admin/expenses'
      preLoaderRoute: typeof WaterAdminExpensesRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/dashboard': {
      id: '/water-admin/dashboard'
      path: '/dashboard'
      fullPath: '/water-admin/dashboard'
      preLoaderRoute: typeof WaterAdminDashboardRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/customers': {
      id: '/water-admin/customers'
      path: '/customers'
      fullPath: '/water-admin/customers'
      preLoaderRoute: typeof WaterAdminCustomersRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/water-admin/cashiers': {
      id: '/water-admin/cashiers'
      path: '/cashiers'
      fullPath: '/water-admin/cashiers'
      preLoaderRoute: typeof WaterAdminCashiersRouteImport
      parentRoute: typeof WaterAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/shops': {
      id: '/super-admin/shops'
      path: '/shops'
      fullPath: '/super-admin/shops'
      preLoaderRoute: typeof SuperAdminShopsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/expenses': {
      id: '/super-admin/expenses'
      path: '/expenses'
      fullPath: '/super-admin/expenses'
      preLoaderRoute: typeof SuperAdminExpensesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/assets': {
      id: '/super-admin/assets'
      path: '/assets'
      fullPath: '/super-admin/assets'
      preLoaderRoute: typeof SuperAdminAssetsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/rb-admin/reports': {
      id: '/rb-admin/reports'
      path: '/reports'
      fullPath: '/rb-admin/reports'
      preLoaderRoute: typeof RbAdminReportsRouteImport
      parentRoute: typeof RbAdminRoute
    }
    '/rb-admin/dashboard': {
      id: '/rb-admin/dashboard'
      path: '/dashboard'
      fullPath: '/rb-admin/dashboard'
      preLoaderRoute: typeof RbAdminDashboardRouteImport
      parentRoute: typeof RbAdminRoute
    }
    '/delivery-admin/reports': {
      id: '/delivery-admin/reports'
      path: '/reports'
      fullPath: '/delivery-admin/reports'
      preLoaderRoute: typeof DeliveryAdminReportsRouteImport
      parentRoute: typeof DeliveryAdminRoute
    }
    '/delivery-admin/fuel': {
      id: '/delivery-admin/fuel'
      path: '/fuel'
      fullPath: '/delivery-admin/fuel'
      preLoaderRoute: typeof DeliveryAdminFuelRouteImport
      parentRoute: typeof DeliveryAdminRoute
    }
    '/delivery-admin/drivers': {
      id: '/delivery-admin/drivers'
      path: '/drivers'
      fullPath: '/delivery-admin/drivers'
      preLoaderRoute: typeof DeliveryAdminDriversRouteImport
      parentRoute: typeof DeliveryAdminRoute
    }
    '/delivery-admin/dashboard': {
      id: '/delivery-admin/dashboard'
      path: '/dashboard'
      fullPath: '/delivery-admin/dashboard'
      preLoaderRoute: typeof DeliveryAdminDashboardRouteImport
      parentRoute: typeof DeliveryAdminRoute
    }
  }
}

interface DeliveryAdminRouteChildren {
  DeliveryAdminDashboardRoute: typeof DeliveryAdminDashboardRoute
  DeliveryAdminDriversRoute: typeof DeliveryAdminDriversRoute
  DeliveryAdminFuelRoute: typeof DeliveryAdminFuelRoute
  DeliveryAdminReportsRoute: typeof DeliveryAdminReportsRoute
}

const DeliveryAdminRouteChildren: DeliveryAdminRouteChildren = {
  DeliveryAdminDashboardRoute: DeliveryAdminDashboardRoute,
  DeliveryAdminDriversRoute: DeliveryAdminDriversRoute,
  DeliveryAdminFuelRoute: DeliveryAdminFuelRoute,
  DeliveryAdminReportsRoute: DeliveryAdminReportsRoute,
}

const DeliveryAdminRouteWithChildren = DeliveryAdminRoute._addFileChildren(
  DeliveryAdminRouteChildren,
)

interface RbAdminRouteChildren {
  RbAdminDashboardRoute: typeof RbAdminDashboardRoute
  RbAdminReportsRoute: typeof RbAdminReportsRoute
}

const RbAdminRouteChildren: RbAdminRouteChildren = {
  RbAdminDashboardRoute: RbAdminDashboardRoute,
  RbAdminReportsRoute: RbAdminReportsRoute,
}

const RbAdminRouteWithChildren =
  RbAdminRoute._addFileChildren(RbAdminRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminAssetsRoute: typeof SuperAdminAssetsRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminExpensesRoute: typeof SuperAdminExpensesRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminShopsRoute: typeof SuperAdminShopsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminAssetsRoute: SuperAdminAssetsRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminExpensesRoute: SuperAdminExpensesRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminShopsRoute: SuperAdminShopsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface WaterAdminRouteChildren {
  WaterAdminCashiersRoute: typeof WaterAdminCashiersRoute
  WaterAdminCustomersRoute: typeof WaterAdminCustomersRoute
  WaterAdminDashboardRoute: typeof WaterAdminDashboardRoute
  WaterAdminExpensesRoute: typeof WaterAdminExpensesRoute
  WaterAdminRefundsRoute: typeof WaterAdminRefundsRoute
  WaterAdminReportsRoute: typeof WaterAdminReportsRoute
  WaterAdminRequestsRoute: typeof WaterAdminRequestsRoute
  WaterAdminStockRoute: typeof WaterAdminStockRoute
}

const WaterAdminRouteChildren: WaterAdminRouteChildren = {
  WaterAdminCashiersRoute: WaterAdminCashiersRoute,
  WaterAdminCustomersRoute: WaterAdminCustomersRoute,
  WaterAdminDashboardRoute: WaterAdminDashboardRoute,
  WaterAdminExpensesRoute: WaterAdminExpensesRoute,
  WaterAdminRefundsRoute: WaterAdminRefundsRoute,
  WaterAdminReportsRoute: WaterAdminReportsRoute,
  WaterAdminRequestsRoute: WaterAdminRequestsRoute,
  WaterAdminStockRoute: WaterAdminStockRoute,
}

const WaterAdminRouteWithChildren = WaterAdminRoute._addFileChildren(
  WaterAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveryAdminRoute: DeliveryAdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RbAdminRoute: RbAdminRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  WaterAdminRoute: WaterAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
